// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComp = `-- name: CreateComp :one
INSERT INTO comps (search_id, external_id, title, price, currency, condition, buying_option, item_url, thumbnail_url, seller_country, excluded)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, search_id, external_id, title, price, currency, condition, buying_option, item_url, thumbnail_url, seller_country, excluded, created_at
`

type CreateCompParams struct {
	SearchID      pgtype.UUID    `json:"search_id"`
	ExternalID    string         `json:"external_id"`
	Title         string         `json:"title"`
	Price         pgtype.Numeric `json:"price"`
	Currency      string         `json:"currency"`
	Condition     *string        `json:"condition"`
	BuyingOption  *string        `json:"buying_option"`
	ItemUrl       *string        `json:"item_url"`
	ThumbnailUrl  *string        `json:"thumbnail_url"`
	SellerCountry *string        `json:"seller_country"`
	Excluded      bool           `json:"excluded"`
}

func (q *Queries) CreateComp(ctx context.Context, arg CreateCompParams) (Comp, error) {
	row := q.db.QueryRow(ctx, createComp,
		arg.SearchID,
		arg.ExternalID,
		arg.Title,
		arg.Price,
		arg.Currency,
		arg.Condition,
		arg.BuyingOption,
		arg.ItemUrl,
		arg.ThumbnailUrl,
		arg.SellerCountry,
		arg.Excluded,
	)
	var i Comp
	err := row.Scan(
		&i.ID,
		&i.SearchID,
		&i.ExternalID,
		&i.Title,
		&i.Price,
		&i.Currency,
		&i.Condition,
		&i.BuyingOption,
		&i.ItemUrl,
		&i.ThumbnailUrl,
		&i.SellerCountry,
		&i.Excluded,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompsBySearch = `-- name: DeleteCompsBySearch :exec
DELETE FROM comps WHERE search_id = $1
`

func (q *Queries) DeleteCompsBySearch(ctx context.Context, searchID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompsBySearch, searchID)
	return err
}

const listCompsBySearch = `-- name: ListCompsBySearch :many
SELECT id, search_id, external_id, title, price, currency, condition, buying_option, item_url, thumbnail_url, seller_country, excluded, created_at FROM comps WHERE search_id = $1 ORDER BY price ASC
`

func (q *Queries) ListCompsBySearch(ctx context.Context, searchID pgtype.UUID) ([]Comp, error) {
	rows, err := q.db.Query(ctx, listCompsBySearch, searchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comp
	for rows.Next() {
		var i Comp
		if err := rows.Scan(
			&i.ID,
			&i.SearchID,
			&i.ExternalID,
			&i.Title,
			&i.Price,
			&i.Currency,
			&i.Condition,
			&i.BuyingOption,
			&i.ItemUrl,
			&i.ThumbnailUrl,
			&i.SellerCountry,
			&i.Excluded,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
