// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: searches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSearch = `-- name: CreateSearch :one
INSERT INTO searches (user_email, image_key, image_width, image_height)
VALUES ($1, $2, $3, $4)
RETURNING id, user_email, status, error_message, image_key, image_width, image_height, title, brand, model, category, condition_notes, search_query, vision_model, vision_raw, confidence, price_source, currency, comp_count, price_mean, price_median, price_min, price_max, price_trimmed_mean, created_at, completed_at
`

type CreateSearchParams struct {
	UserEmail   string `json:"user_email"`
	ImageKey    string `json:"image_key"`
	ImageWidth  *int32 `json:"image_width"`
	ImageHeight *int32 `json:"image_height"`
}

func (q *Queries) CreateSearch(ctx context.Context, arg CreateSearchParams) (Search, error) {
	row := q.db.QueryRow(ctx, createSearch,
		arg.UserEmail,
		arg.ImageKey,
		arg.ImageWidth,
		arg.ImageHeight,
	)
	var i Search
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Status,
		&i.ErrorMessage,
		&i.ImageKey,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.Title,
		&i.Brand,
		&i.Model,
		&i.Category,
		&i.ConditionNotes,
		&i.SearchQuery,
		&i.VisionModel,
		&i.VisionRaw,
		&i.Confidence,
		&i.PriceSource,
		&i.Currency,
		&i.CompCount,
		&i.PriceMean,
		&i.PriceMedian,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceTrimmedMean,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteSearch = `-- name: DeleteSearch :exec
DELETE FROM searches WHERE id = $1
`

func (q *Queries) DeleteSearch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSearch, id)
	return err
}

const getSearch = `-- name: GetSearch :one
SELECT id, user_email, status, error_message, image_key, image_width, image_height, title, brand, model, category, condition_notes, search_query, vision_model, vision_raw, confidence, price_source, currency, comp_count, price_mean, price_median, price_min, price_max, price_trimmed_mean, created_at, completed_at FROM searches WHERE id = $1
`

func (q *Queries) GetSearch(ctx context.Context, id pgtype.UUID) (Search, error) {
	row := q.db.QueryRow(ctx, getSearch, id)
	var i Search
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Status,
		&i.ErrorMessage,
		&i.ImageKey,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.Title,
		&i.Brand,
		&i.Model,
		&i.Category,
		&i.ConditionNotes,
		&i.SearchQuery,
		&i.VisionModel,
		&i.VisionRaw,
		&i.Confidence,
		&i.PriceSource,
		&i.Currency,
		&i.CompCount,
		&i.PriceMean,
		&i.PriceMedian,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceTrimmedMean,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listSearchesForUser = `-- name: ListSearchesForUser :many
SELECT id, user_email, status, error_message, image_key, image_width, image_height, title, brand, model, category, condition_notes, search_query, vision_model, vision_raw, confidence, price_source, currency, comp_count, price_mean, price_median, price_min, price_max, price_trimmed_mean, created_at, completed_at FROM searches
WHERE user_email = $1
  AND (
    created_at < $3
    OR (created_at = $3 AND id < $4)
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListSearchesForUserParams struct {
	UserEmail       string             `json:"user_email"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

func (q *Queries) ListSearchesForUser(ctx context.Context, arg ListSearchesForUserParams) ([]Search, error) {
	rows, err := q.db.Query(ctx, listSearchesForUser,
		arg.UserEmail,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Search
	for rows.Next() {
		var i Search
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.Status,
			&i.ErrorMessage,
			&i.ImageKey,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.Title,
			&i.Brand,
			&i.Model,
			&i.Category,
			&i.ConditionNotes,
			&i.SearchQuery,
			&i.VisionModel,
			&i.VisionRaw,
			&i.Confidence,
			&i.PriceSource,
			&i.Currency,
			&i.CompCount,
			&i.PriceMean,
			&i.PriceMedian,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceTrimmedMean,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleSearchesFailed = `-- name: MarkStaleSearchesFailed :exec
UPDATE searches
SET status = 'failed', error_message = 'orphaned by server restart'
WHERE status IN ('pending', 'identifying', 'pricing')
  AND created_at < now() - interval '5 minutes'
`

func (q *Queries) MarkStaleSearchesFailed(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markStaleSearchesFailed)
	return err
}

const setSearchComplete = `-- name: SetSearchComplete :one
UPDATE searches
SET status = 'complete',
    price_source = $2,
    currency = $3,
    comp_count = $4,
    price_mean = $5,
    price_median = $6,
    price_min = $7,
    price_max = $8,
    price_trimmed_mean = $9,
    completed_at = now()
WHERE id = $1
RETURNING id, user_email, status, error_message, image_key, image_width, image_height, title, brand, model, category, condition_notes, search_query, vision_model, vision_raw, confidence, price_source, currency, comp_count, price_mean, price_median, price_min, price_max, price_trimmed_mean, created_at, completed_at
`

type SetSearchCompleteParams struct {
	ID               pgtype.UUID    `json:"id"`
	PriceSource      *string        `json:"price_source"`
	Currency         *string        `json:"currency"`
	CompCount        *int32         `json:"comp_count"`
	PriceMean        pgtype.Numeric `json:"price_mean"`
	PriceMedian      pgtype.Numeric `json:"price_median"`
	PriceMin         pgtype.Numeric `json:"price_min"`
	PriceMax         pgtype.Numeric `json:"price_max"`
	PriceTrimmedMean pgtype.Numeric `json:"price_trimmed_mean"`
}

func (q *Queries) SetSearchComplete(ctx context.Context, arg SetSearchCompleteParams) (Search, error) {
	row := q.db.QueryRow(ctx, setSearchComplete,
		arg.ID,
		arg.PriceSource,
		arg.Currency,
		arg.CompCount,
		arg.PriceMean,
		arg.PriceMedian,
		arg.PriceMin,
		arg.PriceMax,
		arg.PriceTrimmedMean,
	)
	var i Search
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Status,
		&i.ErrorMessage,
		&i.ImageKey,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.Title,
		&i.Brand,
		&i.Model,
		&i.Category,
		&i.ConditionNotes,
		&i.SearchQuery,
		&i.VisionModel,
		&i.VisionRaw,
		&i.Confidence,
		&i.PriceSource,
		&i.Currency,
		&i.CompCount,
		&i.PriceMean,
		&i.PriceMedian,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceTrimmedMean,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setSearchFailed = `-- name: SetSearchFailed :one
UPDATE searches
SET status = 'failed', error_message = $2
WHERE id = $1
RETURNING id, user_email, status, error_message, image_key, image_width, image_height, title, brand, model, category, condition_notes, search_query, vision_model, vision_raw, confidence, price_source, currency, comp_count, price_mean, price_median, price_min, price_max, price_trimmed_mean, created_at, completed_at
`

type SetSearchFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) SetSearchFailed(ctx context.Context, arg SetSearchFailedParams) (Search, error) {
	row := q.db.QueryRow(ctx, setSearchFailed, arg.ID, arg.ErrorMessage)
	var i Search
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Status,
		&i.ErrorMessage,
		&i.ImageKey,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.Title,
		&i.Brand,
		&i.Model,
		&i.Category,
		&i.ConditionNotes,
		&i.SearchQuery,
		&i.VisionModel,
		&i.VisionRaw,
		&i.Confidence,
		&i.PriceSource,
		&i.Currency,
		&i.CompCount,
		&i.PriceMean,
		&i.PriceMedian,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceTrimmedMean,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setSearchIdentification = `-- name: SetSearchIdentification :one
UPDATE searches
SET status = 'pricing',
    title = $2,
    brand = $3,
    model = $4,
    category = $5,
    condition_notes = $6,
    search_query = $7,
    vision_model = $8,
    vision_raw = $9,
    confidence = $10
WHERE id = $1
RETURNING id, user_email, status, error_message, image_key, image_width, image_height, title, brand, model, category, condition_notes, search_query, vision_model, vision_raw, confidence, price_source, currency, comp_count, price_mean, price_median, price_min, price_max, price_trimmed_mean, created_at, completed_at
`

type SetSearchIdentificationParams struct {
	ID             pgtype.UUID    `json:"id"`
	Title          *string        `json:"title"`
	Brand          *string        `json:"brand"`
	Model          *string        `json:"model"`
	Category       *string        `json:"category"`
	ConditionNotes *string        `json:"condition_notes"`
	SearchQuery    *string        `json:"search_query"`
	VisionModel    *string        `json:"vision_model"`
	VisionRaw      []byte         `json:"vision_raw"`
	Confidence     pgtype.Numeric `json:"confidence"`
}

func (q *Queries) SetSearchIdentification(ctx context.Context, arg SetSearchIdentificationParams) (Search, error) {
	row := q.db.QueryRow(ctx, setSearchIdentification,
		arg.ID,
		arg.Title,
		arg.Brand,
		arg.Model,
		arg.Category,
		arg.ConditionNotes,
		arg.SearchQuery,
		arg.VisionModel,
		arg.VisionRaw,
		arg.Confidence,
	)
	var i Search
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Status,
		&i.ErrorMessage,
		&i.ImageKey,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.Title,
		&i.Brand,
		&i.Model,
		&i.Category,
		&i.ConditionNotes,
		&i.SearchQuery,
		&i.VisionModel,
		&i.VisionRaw,
		&i.Confidence,
		&i.PriceSource,
		&i.Currency,
		&i.CompCount,
		&i.PriceMean,
		&i.PriceMedian,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceTrimmedMean,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateSearchQuery = `-- name: UpdateSearchQuery :one
UPDATE searches
SET status = 'pricing', search_query = $2
WHERE id = $1
RETURNING id, user_email, status, error_message, image_key, image_width, image_height, title, brand, model, category, condition_notes, search_query, vision_model, vision_raw, confidence, price_source, currency, comp_count, price_mean, price_median, price_min, price_max, price_trimmed_mean, created_at, completed_at
`

type UpdateSearchQueryParams struct {
	ID          pgtype.UUID `json:"id"`
	SearchQuery *string     `json:"search_query"`
}

func (q *Queries) UpdateSearchQuery(ctx context.Context, arg UpdateSearchQueryParams) (Search, error) {
	row := q.db.QueryRow(ctx, updateSearchQuery, arg.ID, arg.SearchQuery)
	var i Search
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Status,
		&i.ErrorMessage,
		&i.ImageKey,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.Title,
		&i.Brand,
		&i.Model,
		&i.Category,
		&i.ConditionNotes,
		&i.SearchQuery,
		&i.VisionModel,
		&i.VisionRaw,
		&i.Confidence,
		&i.PriceSource,
		&i.Currency,
		&i.CompCount,
		&i.PriceMean,
		&i.PriceMedian,
		&i.PriceMin,
		&i.PriceMax,
		&i.PriceTrimmedMean,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
